# dbt Connection Profile
# ======================

hm_fashion_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: airflow
      password: airflow
      dbname: ecommerce
      schema: raw
      threads: 4